import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F5F7FB" },
  container: { flexGrow: 1, padding: 20 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#E8EEFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  backButtonText: { fontSize: 26, color: "#1E3A8A" },
  headerTitle: { fontSize: 24, fontWeight: "700", color: "#111827" },
  headerSubtitle: { marginTop: 3, color: "#6B7280" },
  infoCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 14,
    borderRadius: 14,
    backgroundColor: "#E8EEFF",
    marginBottom: 16,
  },
  infoIcon: { fontSize: 22, marginRight: 10 },
  infoText: { flex: 1, color: "#1E3A8A", lineHeight: 19 },
  loader: { marginTop: 70 },
  supplierList: { gap: 12 },
  supplierCard: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
  },
  supplierHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  supplierNameContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  supplierIcon: { fontSize: 22, marginRight: 8 },
  supplierName: {
    flex: 1,
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
  },
  progressValue: { fontSize: 20, fontWeight: "700", color: "#1E3A8A" },
  progressTrack: {
    height: 12,
    borderRadius: 6,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  progressFill: {
    height: "100%",
    borderRadius: 6,
    backgroundColor: "#2563EB",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  stat: { fontSize: 11, color: "#6B7280" },
  emptyState: { alignItems: "center", marginTop: 70, paddingHorizontal: 20 },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
    textAlign: "center",
  },
  emptyDescription: {
    marginTop: 7,
    color: "#6B7280",
    textAlign: "center",
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: "#1E3A8A",
  },
  retryText: { color: "#FFFFFF", fontWeight: "700" },
});

export default styles;
