import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F5F7FB" },
  container: { flex: 1, padding: 20 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 16 },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#E8EEFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  backText: { fontSize: 26, color: "#1E3A8A" },
  title: { fontSize: 23, fontWeight: "700", color: "#111827" },
  subtitle: { marginTop: 3, color: "#6B7280" },
  tabs: { gap: 8, paddingBottom: 14 },
  tab: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  activeTab: { backgroundColor: "#1E3A8A", borderColor: "#1E3A8A" },
  tabText: { color: "#4B5563", fontWeight: "600" },
  activeTabText: { color: "#FFFFFF" },
  addButton: {
    alignItems: "center",
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: "#1E3A8A",
    marginBottom: 14,
  },
  addButtonText: { color: "#FFFFFF", fontWeight: "700" },
  loader: { marginTop: 60 },
  list: { gap: 12, paddingBottom: 30 },
  card: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#E8EEFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  avatarText: { fontSize: 19, fontWeight: "700", color: "#1E3A8A" },
  identity: { flex: 1 },
  name: { fontSize: 16, fontWeight: "700", color: "#111827" },
  detail: { marginTop: 3, color: "#6B7280", fontSize: 12 },
  actionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: "#F1F5F9",
  },
  permissionLabel: { color: "#4B5563", fontSize: 13 },
  smallButton: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 15,
    backgroundColor: "#6B7280",
  },
  activeButton: { backgroundColor: "#16A34A" },
  blockedButton: { backgroundColor: "#16A34A" },
  buttonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 12 },
  outlineButton: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#1E3A8A",
  },
  outlineText: { color: "#1E3A8A", fontWeight: "700", fontSize: 12 },
  removeButton: { marginTop: 10, alignItems: "center", padding: 9 },
  removeText: { color: "#DC2626", fontWeight: "700" },
  statusText: { color: "#4B5563", marginTop: 3 },
  supplierActions: { marginTop: 3 },
  actionButtons: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  approveButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "#16A34A",
  },
  rejectButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "#DC2626",
  },
  empty: { textAlign: "center", color: "#6B7280", marginTop: 60 },
});

export default styles;
