import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F5F7FB" },
  container: { flexGrow: 1, padding: 20 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#E8EEFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  backButtonText: { fontSize: 26, color: "#1E3A8A" },
  downloadButton: {
    marginLeft: "auto",
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 16,
    backgroundColor: "#1E3A8A",
  },
  downloadButtonText: { color: "#FFFFFF", fontWeight: "700", fontSize: 12 },
  headerTitle: { fontSize: 24, fontWeight: "700", color: "#111827" },
  headerSubtitle: { marginTop: 3, color: "#6B7280" },
  periodTabs: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  periodTab: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 11,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  activePeriodTab: { backgroundColor: "#1E3A8A", borderColor: "#1E3A8A" },
  periodText: { fontWeight: "600", color: "#4B5563" },
  activePeriodText: { color: "#FFFFFF" },
  totalCard: {
    padding: 18,
    borderRadius: 18,
    backgroundColor: "#1E3A8A",
    marginBottom: 16,
  },
  totalLabel: { color: "#DBEAFE", fontSize: 14 },
  totalValue: {
    color: "#FFFFFF",
    fontSize: 27,
    fontWeight: "700",
    marginTop: 5,
  },
  loader: { marginTop: 70 },
  chartCard: {
    padding: 16,
    borderRadius: 18,
    backgroundColor: "#FFFFFF",
    elevation: 2,
  },
  chartTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 20,
  },
  chart: {
    minHeight: 220,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
  },
  barColumn: { flex: 1, alignItems: "center", minWidth: 38 },
  barValue: { fontSize: 9, color: "#6B7280", marginBottom: 4 },
  barArea: { height: 150, justifyContent: "flex-end" },
  bar: {
    width: 22,
    minHeight: 8,
    borderRadius: 8,
    backgroundColor: "#3B82F6",
  },
  barLabel: {
    fontSize: 9,
    color: "#4B5563",
    marginTop: 7,
    textAlign: "center",
  },
  orderCount: { fontSize: 8, color: "#9CA3AF", marginTop: 3 },
  emptyState: { alignItems: "center", marginTop: 70, paddingHorizontal: 20 },
  emptyIcon: { fontSize: 40, marginBottom: 12 },
  emptyTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#111827",
    textAlign: "center",
  },
  emptyDescription: {
    marginTop: 7,
    color: "#6B7280",
    textAlign: "center",
  },
  retryButton: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 18,
    backgroundColor: "#1E3A8A",
  },
  retryText: { color: "#FFFFFF", fontWeight: "700" },
});

export default styles;
