import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F6FF" },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F6FF",
  },
  loadingText: { marginTop: 12, color: "#555" },
  header: {
    height: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 18,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E5E7EB",
  },
  backButton: { width: 40, height: 40, justifyContent: "center" },
  backButtonText: { fontSize: 28, color: "#1E3A8A" },
  headerTitle: { fontSize: 20, fontWeight: "700", color: "#1F2937" },
  headerSpace: { width: 40 },
  content: { alignItems: "center", padding: 22, paddingBottom: 40 },
  imageContainer: { position: "relative", marginTop: 12 },
  profileImage: { width: 110, height: 110, borderRadius: 55 },
  avatar: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: "#1E3A8A",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: { color: "#FFFFFF", fontSize: 44, fontWeight: "700" },
  cameraButton: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
    justifyContent: "center",
    alignItems: "center",
    elevation: 3,
  },
  cameraText: { fontSize: 17 },
  changePhotoText: {
    color: "#1E3A8A",
    fontWeight: "700",
    marginTop: 12,
    marginBottom: 28,
  },
  label: {
    alignSelf: "stretch",
    color: "#374151",
    fontWeight: "600",
    marginBottom: 7,
    marginTop: 12,
  },
  input: {
    alignSelf: "stretch",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D1D5DB",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
    color: "#1F2937",
  },
  saveButton: {
    alignSelf: "stretch",
    alignItems: "center",
    backgroundColor: "#1E3A8A",
    borderRadius: 12,
    paddingVertical: 15,
    marginTop: 30,
  },
  disabledButton: { opacity: 0.65 },
  saveButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "700" },
  cancelButton: { paddingVertical: 16 },
  cancelButtonText: { color: "#6B7280", fontWeight: "600" },
});

export default styles;
