import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F5F7FB" },
  loadingScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F5F7FB",
  },
  container: { flexGrow: 1, padding: 20 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 22 },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#E8EEFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  backText: { fontSize: 26, color: "#1E3A8A" },
  title: { fontSize: 23, fontWeight: "700", color: "#111827" },
  subtitle: { marginTop: 3, color: "#6B7280" },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#111827",
    marginBottom: 12,
  },
  metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginBottom: 14 },
  metricCard: {
    width: "48%",
    minHeight: 112,
    padding: 13,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  metricIcon: { fontSize: 21, marginBottom: 7 },
  metricValue: { fontSize: 17, fontWeight: "700", color: "#1E3A8A" },
  metricLabel: { marginTop: 4, fontSize: 12, color: "#6B7280" },
  notice: {
    padding: 13,
    borderRadius: 13,
    backgroundColor: "#FEF3C7",
    marginBottom: 24,
  },
  noticeText: { color: "#92400E", lineHeight: 19, fontSize: 12 },
  settingsCard: {
    padding: 16,
    borderRadius: 17,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 15,
    marginBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  settingTitle: { fontSize: 16, fontWeight: "700", color: "#111827" },
  settingDescription: { marginTop: 3, color: "#6B7280" },
  inputLabel: { marginTop: 10, marginBottom: 6, color: "#4B5563", fontSize: 13 },
  input: {
    minHeight: 44,
    paddingHorizontal: 13,
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    color: "#111827",
  },
  saveButton: {
    minHeight: 46,
    marginTop: 20,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1E3A8A",
  },
  saveText: { color: "#FFFFFF", fontWeight: "700" },
});

export default styles;
