import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F5F7FB" },
  container: { padding: 20, paddingBottom: 40 },
  header: { flexDirection: "row", alignItems: "center", marginBottom: 22 },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#E8EEFF",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  backButtonText: { fontSize: 25, color: "#1E3A8A", marginTop: -2 },
  headerContent: { flex: 1 },
  headerTitle: { fontSize: 26, fontWeight: "800", color: "#111827" },
  headerSubtitle: { marginTop: 4, fontSize: 13, color: "#6B7280" },
  summaryRow: { flexDirection: "row", gap: 10, marginBottom: 18 },
  summaryCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    padding: 13,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  summaryValue: { fontSize: 22, fontWeight: "800", color: "#1E3A8A" },
  summaryLabel: { marginTop: 3, fontSize: 12, color: "#6B7280" },
  warningText: { color: "#D97706" },
  dangerText: { color: "#DC2626" },
  searchInput: {
    height: 48,
    backgroundColor: "#FFFFFF",
    borderRadius: 13,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    paddingHorizontal: 15,
    fontSize: 14,
    color: "#111827",
    marginBottom: 14,
  },
  filterList: { gap: 8, paddingBottom: 18 },
  filterButton: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 20,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  activeFilterButton: { backgroundColor: "#1E3A8A", borderColor: "#1E3A8A" },
  filterText: { fontSize: 12, fontWeight: "700", color: "#6B7280" },
  activeFilterText: { color: "#FFFFFF" },
  loader: { marginTop: 55 },
  productList: { gap: 12 },
  productCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 15,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  productDetails: { flex: 1, paddingRight: 10 },
  productName: { fontSize: 16, fontWeight: "800", color: "#111827" },
  productCategory: { marginTop: 4, fontSize: 12, color: "#1E3A8A" },
  supplierName: { marginTop: 7, fontSize: 12, color: "#6B7280" },
  stockColumn: { alignItems: "flex-end" },
  stockQuantity: {
    fontSize: 14,
    fontWeight: "800",
    color: "#111827",
    marginBottom: 7,
  },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 5, borderRadius: 20 },
  in_stockBadge: { backgroundColor: "#ECFDF5" },
  low_stockBadge: { backgroundColor: "#FFFBEB" },
  out_of_stockBadge: { backgroundColor: "#FEF2F2" },
  statusText: { fontSize: 11, fontWeight: "700" },
  in_stockText: { color: "#16A34A" },
  low_stockText: { color: "#D97706" },
  out_of_stockText: { color: "#DC2626" },
  emptyState: { alignItems: "center", paddingTop: 55 },
  emptyIcon: { fontSize: 52, marginBottom: 14 },
  emptyTitle: { fontSize: 18, fontWeight: "800", color: "#111827" },
  emptyDescription: {
    marginTop: 8,
    color: "#6B7280",
    fontSize: 14,
    textAlign: "center",
  },
  retryButton: {
    marginTop: 18,
    backgroundColor: "#1E3A8A",
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 11,
  },
  retryText: { color: "#FFFFFF", fontWeight: "700" },
});

export default styles;
